# deployment-and-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devicemanagement-deployment
  namespace: team-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devicemanagement
  template:
    metadata:
      labels:
        app: devicemanagement
    spec:
      initContainers:
        - name: init-logs
          image: busybox:latest
          command: ["sh", "-c", "mkdir -p /app/logs && chmod -R 777 /app/logs"]
          volumeMounts:
            - name: app-log-volume
              mountPath: /app/logs
      volumes:
        - name: app-log-volume
          emptyDir: {}
      containers:
        - name: devicemanagement
          image: dvm-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3079
          volumeMounts:
            - name: app-log-volume
              mountPath: /app/logs
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb+srv://root:root@cluster0.lhvo556.mongodb.net/Abc?retryWrites=true&w=majority"
            - name: SPRING_REDIS_HOST
              value: "redis-service.default.svc.cluster.local"
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_REDIS_PASSWORD
              value: "@#12345678"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 3079
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 3079
            initialDelaySeconds: 90
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
        - name: log-reader
          image: log-reader-app:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: app-log-volume
              mountPath: /app/logs
          env:
            - name: LOG_READER_PATH
              value: "/app/logs/app.log"
          livenessProbe:
            exec:
              command: ["sh", "-c", "test -d /app/logs"]
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: devicemanagement-service
  namespace: team-a
spec:
  type: NodePort
  selector:
    app: devicemanagement
  ports:
    - port: 3079
      targetPort: 3079
      nodePort: 30080
